trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pytest tests --junitxml=TEST-results.xml
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-results.xml'
    testRunTitle: 'Test Results'

- task: CopyFiles@2
  inputs:
    contents: '**/src/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/src'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/src'
    artifactName: 'src'
